# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r: [ 'release', 'devel' ]
    name: R ${{ matrix.r }} check
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-tinytex@v2
      - name: add TeX deps
        run: tlmgr install grfext
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          sudo apt-get install -y libv8-dev
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install V8 package
        run: Rscript -e "install.packages('V8')"
      - name: Check package
        run: R CMD build --compact-vignettes=both . && R CMD check *tar.gz --as-cran
